### ISSUE TITLE
add image for playlist/track ?

### ISSUE THREAD

**Issue by gordielachance** [njh/ruby-playlist#13]
Hi, is there a way to assign an image to a playlist and to tracks ?
Thanks !

**Comment by njh** [comment]
Hi

No there isn't at the moment.

Were you thinking Image URLs for the XSPF file format?

Shouldn't be very hard to add...

**Comment by gordielachance** [comment]
Yes. Since XSPF is a standard (unlike the other formats), it would be nice to have more properties matching it.

**Comment by njh** [comment]
I have added support for image on tracks and playlists in 5168ad409100ad2edf453c9253d135d1b1db1bd5.
And support for images in XSPF in 4e2565957ecd951deaef4018e4e0e47ca4ad9815.

I will try and get version 1.2.0 released tonight

**Comment by gordielachance** [comment]
amazing !
thanks.

**Comment by njh** [comment]
Published! https://rubygems.org/gems/playlist/versions/1.2.0

**Comment by gordielachance** [comment]
...installed ! :)thanks.
