### ISSUE TITLE
generating XSPF is broken ?

### ISSUE THREAD

**Issue by gordielachance** [njh/ruby-playlist#14]
Hi again !
Looks like generating XSPF playlists is broken, the artist is missing in the output !

    puts Playlist::Format::SimpleText.generate(playlist)

give me
    

>     Victor Wooten - Flip Flop (Bonus Track)

while

    puts Playlist::Format::XSPF.generate(playlist)

gives me 

>     <track>
>       <title>Flip Flop (Bonus Track)</title>
>       <album>A Show of Hands 15</album>
>     </track>

Any chance that you could fix this ?
Thanks a lot for your work !

**Comment by njh** [comment]
Arg!

This is a problem with different types of Contributions to piece of music.
I interpreted that the 'Artist' field, normally means 'Performer'.
But sometimes it will mean Composer.
And sometimes there will be multiple contributors in the same field.

XSPF only has a 'Creator' role which is deliberately vague.
I will have to check to see which bit is going wrong.

I presume you are doing something like this first?

```ruby
playlist = Playlist.new
playlist.add_track(
  :artist => "Victor Wooten",
  :title => "Flip Flop (Bonus Track)",
  :album => "A Show of Hands 15"
)
```

**Comment by gordielachance** [comment]
I'm using the _:performer_ property, but yes, seems this is not clear.

**Comment by njh** [comment]
I made some changes but forgot to add a comment here.

* `#creator=` will set the name of a contributor, but with an undefined role
* `#creator` will now return a string with the names of all the contributors (previously it was only of undefined role)
* `#artist` is now an alias for `#creator` (previously alias for `#performer`)
* `#artist=` is now an alias for `#creator=` (previously alias for `#performer=`)

Are you able to use the version in Git and test it before I make a release?

**Comment by gordielachance** [comment]
Hi, I could try to test but I'm quite new to Ruby.  
How can I test a git version ?
Tnx

**Comment by gordielachance** [comment]
I can confirm it now (1.3.0) works with both _:performer_ and _:artist_.
Thanks
